### ISSUE TITLE
hide_zero_series should affect interactive legend as well

### ISSUE THREAD

**Issue by kretes** [urbanairship/tessera#472]
Currently when I set hide_zero_series on standard time series to true - I do not get empty series on the chart, but when in interactive mode I look at the legend - it displays zero series still. 

Zero series should be removed from this legend as well

**Comment by aalpern** [comment]
Agreed.

**Comment by aalpern** [comment]
Hmm - looks like it already tries to do that, with the exact same conditional in the legend as is in the chart rendering: https://github.com/urbanairship/tessera/blob/master/src/ts/charts/flot.ts#L208 and in my testing it's actually working fine.

**Comment by aalpern** [comment]
Ah - were you referring to the rollover data shown when hovering the mouse over the graph?

**Comment by kretes** [comment]
yes, I'm referring to rollover data, shown when in 'interactive mode'

**Comment by aalpern** [comment]
Got it - I misunderstood what you meant by "legend". 

It's actually by design that all the series are shown in the mouseover, so that you can see all the series that were returned if you want to, while saving space on the static legend. I can see a strong case for going the other way with it too, though.

**Comment by aalpern** [comment]
Done
